language: php
php:
  - 7.2
os:
  - linux
stages:
  - test
jobs:
  include:
    - stage: test
      install:
        - composer self-update
        - composer require squizlabs/php_codesniffer:dev-master
        - composer install
        - phpenv rehash
      script:
        - vendor/bin/phpcs --standard=phpcs.xml
        - composer test