language: php
php:
  - 7.4
os:
  - linux
stages:
  - test
jobs:
  include:
    - stage: test
      install:
        - composer self-update
        - composer install
        - phpenv rehash
      script:
        - composer cs-check
        - composer test:unit
        - composer test:integration
